#!/usr/bin/env python3
"""Scrapes PGA Tour / Korn Ferry / PGA Tour Americas schedules and writes a SQL
seed file for the `tournaments` table. Run the output in the Supabase SQL editor.

Usage:
    python3 scripts/scrape_schedules.py [--truncate] [--out supabase/seed_tournaments.sql]

The tour sites render their schedule client-side, but the data used for that
render ships embedded in the page as a Next.js __NEXT_DATA__ JSON blob (under
props.pageProps.dehydratedState.queries), so a plain HTTP GET + JSON parse is
enough — no browser automation needed.
"""

import argparse
import json
import re
import sys
from datetime import datetime

import requests

SOURCES = [
    ("https://www.pgatour.com/schedule", "PGA"),
    ("https://www.pgatour.com/korn-ferry-tour/schedule", "Korn Ferry"),
    ("https://www.pgatour.com/americas/schedule", "Americas"),
]

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
    )
}

NEXT_DATA_RE = re.compile(
    r'<script id="__NEXT_DATA__"[^>]*>(.*?)</script>', re.S
)


def fetch_tournaments(url: str) -> list[dict]:
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()

    match = NEXT_DATA_RE.search(resp.text)
    if not match:
        raise RuntimeError(f"Could not find __NEXT_DATA__ on {url}")

    data = json.loads(match.group(1))
    queries = data["props"]["pageProps"]["dehydratedState"]["queries"]
    schedule_queries = [q for q in queries if q["queryKey"][0] == "schedule"]
    if not schedule_queries:
        raise RuntimeError(f"Could not find a schedule query on {url}")

    return schedule_queries[0]["state"]["data"]["tournaments"]


def parse_dates(month: str, year: str, display_date: str):
    """"Jan 15 - 18" / "Jan 29 - Feb 1" / "Dec 29 - Jan 1" -> (start date, end date)."""
    parts = [p.strip() for p in display_date.split(" - ")]
    if len(parts) != 2:
        return None, None

    start_part, end_part = parts
    year = int(year)

    try:
        start_dt = datetime.strptime(f"{start_part} {year}", "%b %d %Y")
    except ValueError:
        return None, None

    if end_part.isdigit():
        end_part = f"{start_part.split()[0]} {end_part}"

    try:
        end_dt = datetime.strptime(f"{end_part} {year}", "%b %d %Y")
    except ValueError:
        return None, None

    if end_dt < start_dt:
        end_dt = end_dt.replace(year=year + 1)

    return start_dt.date(), end_dt.date()


def build_location(course_data: dict | None) -> str:
    if not course_data:
        return ""
    city = (course_data.get("city") or "").strip()
    country = (course_data.get("country") or "").strip()
    state = (course_data.get("stateCode") or "").strip()

    if country == "United States of America":
        parts = [p for p in (city, state) if p]
    else:
        parts = [p for p in (city, country) if p]
    return ", ".join(parts)


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out", default="supabase/seed_tournaments.sql", help="Output SQL file path"
    )
    parser.add_argument(
        "--truncate",
        action="store_true",
        help="Prefix the output with `delete from tournaments;` for a clean reload",
    )
    args = parser.parse_args()

    rows = []
    skipped = 0

    for url, tour_name in SOURCES:
        print(f"Fetching {tour_name} schedule from {url} ...", file=sys.stderr)
        tournaments = fetch_tournaments(url)
        for t in tournaments:
            start, end = parse_dates(t.get("month", ""), t.get("year", ""), t.get("displayDate", ""))
            if not start or not end:
                skipped += 1
                print(f"  skipping (unparseable date): {t.get('name')!r}", file=sys.stderr)
                continue

            location = build_location(t.get("courseData"))
            rows.append(
                (sql_escape(t["name"]), tour_name, sql_escape(location), start.isoformat(), end.isoformat())
            )
        print(f"  {len(tournaments)} tournaments found", file=sys.stderr)

    if not rows:
        print("No tournaments scraped — aborting without writing a file.", file=sys.stderr)
        sys.exit(1)

    lines = [
        "-- Generated by scripts/scrape_schedules.py",
        "-- Run this in the Supabase SQL editor (Project > SQL Editor > New query).",
        "",
    ]
    if args.truncate:
        lines.append("delete from tournaments;")
        lines.append("")

    lines.append("insert into tournaments (name, tour, location, start_date, end_date) values")
    value_lines = [
        f"  ('{name}', '{tour}', '{location}', '{start}', '{end}')"
        for name, tour, location, start, end in rows
    ]
    lines.append(",\n".join(value_lines) + ";")
    lines.append("")

    with open(args.out, "w") as f:
        f.write("\n".join(lines))

    print(f"\nWrote {len(rows)} tournaments to {args.out} ({skipped} skipped).", file=sys.stderr)


if __name__ == "__main__":
    main()
